from django.urls import path
from . import views
urlpatterns = [
    path('index/', views.index),
    path('login/', views.admin_login),
    path('logout/', views.logout),
    path('addstu/', views.addstu),
    path('addsem/', views.addsem),
    path('adddep/', views.adddep),
    path('adddeg/', views.adddeg),
    path('addsub/', views.addsub),
    path('addfac/', views.addfac),
    path('showdeg/', views.show_deg),
    path('show_dep/', views.show_dep),
    path('show_sem/', views.show_sem),
    path('show_sub/', views.show_sub),
    path('show_fac/', views.show_fac),
    path('show_stu/', views.show_stu),
    path('edit/<int:id>/', views.edit),
    path('dep_edit/<int:id>/', views.dep_edit),
    path('sem_edit/<int:id>/', views.sem_edit),
    path('sub_edit/<int:id>/', views.sub_edit),
    path('fac_edit/<int:id>/', views.fac_edit),
    path('stu_edit/<int:id>/', views.stu_edit),
    path('update/<int:id>/', views.update),
    path('dep_update/<int:id>/', views.dep_update),
    path('sem_update/<int:id>/', views.sem_update),
    path('sub_update/<int:id>/', views.sub_update),
    path('fac_update/<int:id>/', views.fac_update),
    path('stu_update/<int:id>/', views.stu_update),
    path('delete/<int:id>/', views.destroy),
    path('dep_delete/<int:id>/', views.dep_destroy),
    path('sem_delete/<int:id>/', views.sem_destroy),
    path('sub_delete/<int:id>/', views.sub_destroy),
    path('fac_delete/<int:id>/', views.fac_destroy),
    path('stu_delete/<int:id>/', views.stu_destroy),
]
