# Generated by Django 4.0.2 on 2022-02-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=300)),
                ('deg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.degree')),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_number', models.IntegerField()),
                ('deg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.degree')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30)),
                ('sub_code', models.IntegerField()),
                ('sub_textbook', models.CharField(max_length=300)),
                ('deg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.degree')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fn', models.CharField(max_length=30)),
                ('ln', models.CharField(max_length=30)),
                ('enrollment', models.IntegerField()),
                ('gender', models.CharField(choices=[(1, 'MALE'), (2, 'FEMALE')], max_length=20)),
                ('status', models.CharField(choices=[(1, 'STUDYING'), (2, 'STUDIED'), (3, 'BREAK')], max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('parent_number', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('deg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.degree')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fn', models.CharField(max_length=30)),
                ('ln', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(1, 'MALE'), (2, 'FEMALE')], max_length=20)),
                ('hod', models.CharField(choices=[(1, 'YES'), (2, 'NO')], max_length=10)),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to='')),
                ('deg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.degree')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
            ],
        ),
    ]
