# Generated by Django 4.0.2 on 2022-02-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_department_dep_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='sem_id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='sub_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='student.subject'),
            preserve_default=False,
        ),
    ]
