# Generated by Django 4.0.2 on 2022-02-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_faculty_sem_id_faculty_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='hod',
            field=models.CharField(choices=[('1', 'YES'), ('2', 'NO')], max_length=10),
        ),
    ]
