# Generated by Django 4.0.2 on 2022-02-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_faculty_gender_alter_faculty_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('1', 'STUDYING'), ('2', 'STUDIED'), ('3', 'BREAK')], max_length=30),
        ),
    ]
