# Generated by Django 3.2.9 on 2022-03-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
