# Generated by Django 3.2.9 on 2022-03-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img',
            field=models.FileField(default=-1, upload_to=''),
            preserve_default=False,
        ),
    ]
